"""
Django settings for pythonauth project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w^)vu11uof+d(jwtv-yzbooelfn&invp-fn=g-or-zi1izlh+4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'adlsauth.apps.AdlsauthConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pythonauth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pythonauth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# my constants
CONSTANTS = {
#	'CLIENT_ID': '0913cb0a-56d2-4c48-9930-5fcedc97b819',
#	'CLIENT_KEY': 'PgNdHW6o3cc+RIBGT8MO+kL69HpC+1UEk9MANCx8kTs=',
	'CLIENT_ID': 'c0674908-2d6f-4d99-9098-47e774c7e96f',
	'CLIENT_KEY': 'N+OXhXK0emc5W0MnXVfT5WNSEgvkSF+6u5a9LD1lziA=',
	'STEP_1_TEMPLATE_NAME': 'adlsauth/step1.html',
	'STEP_2_TEMPLATE_NAME': 'adlsauth/step2.html',
	'STEP_3_TEMPLATE_NAME': 'adlsauth/step3.html',
	'STEP_4_TEMPLATE_NAME': 'adlsauth/step4.html',
	'STEP_5_TEMPLATE_NAME': 'adlsauth/step5.html',
	'STEP_1_TEMPLATE_NAME_LIVE': 'adlsauth/step1_live.html',
	'STEP_2_TEMPLATE_NAME_LIVE': 'adlsauth/step2_live.html',
	'STEP_3_TEMPLATE_NAME_LIVE': 'adlsauth/step3_live.html',
	'STEP_4_TEMPLATE_NAME_LIVE': 'adlsauth/step4_live.html',
	'STEP_5_TEMPLATE_NAME_LIVE': 'adlsauth/step5_live.html',
	'REDIRECT_URI': 'http://localhost:8080/adlsauth/step2/',
	'REDIRECT_URI_LIVE': 'http://localhost:8000/adlsauth/step2_live/',
#	'AUTHORIZATION_BASE_URL': 'https://login.microsoftonline.com/9fa1452f-f213-4a58-bc32-3575cd80dcd8/oauth2/authorize',
#	'BASE_TOKEN_URL': 'https://login.microsoftonline.com/9fa1452f-f213-4a58-bc32-3575cd80dcd8/oauth2/token',
	'AUTHORIZATION_BASE_URL': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/authorize',
	'BASE_TOKEN_URL': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token',
	'RESOURCE_URI': 'https://management.core.windows.net/',
    'DATA_LAKE_URI': 'https://gidatalake1.azuredatalakestore.net/webhdfs/v1/gisampledata/',
    'DATA_LAKE_OPERATION': 'op',
    'DATA_LAKE_LIST_FOLDERS': 'LISTSTATUS',
	'GET_SUBSCRIPTIONS_URL': 'https://management.core.windows.net/subscriptions',
	'MS_API_VERSION_HEADER': 'x-ms-version',
    'MS_API_VERSION_DATA_LAKE_VALUE' : 'api-version=2016-11-01',
	'MS_API_VERSION_HEADER_VALUE': '2013-08-01'
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
